Личный проект: обратная сторона реальности
htmlacademy-react/54972-what-to-watch-5 pull request #5
Opened 2020-10-18 15:31 UTC by AeShevch

2020-10-19 07:25 UTC, abeluzhenko requested changes
Все-таки, по критериям, все компоненты должны лежать в папке `components`, давай перенесем их из `pages`, переименовывать не нужно.

2020-10-19 07:25 UTC, abeluzhenko commented on src/mocks/films.js
> +];
Здесь можно было добавить маппинг с добавлением св-ва id, чтобы не копировать код для каждого элемента.

2020-10-19 07:25 UTC, abeluzhenko commented on src/pages/main-page/main-page.jsx
> +  const currentMovie = movies[0];
Что лишний раз не использовать доступ по индексу, можно делать так:
`const [currentMovie] = movies;`

2020-10-19 07:28 UTC, abeluzhenko requested changes

2020-10-19 07:28 UTC, abeluzhenko commented on src/components/app/app.jsx
> +              related={movies.slice(0, 4)}
Здесь было бы гораздо понятнее, если бы вместо числа `4` использовалась константа

2020-10-19 08:45 UTC, AeShevch commented on src/mocks/films.js
> +];
Понял

2020-10-19 08:45 UTC, AeShevch commented on src/pages/main-page/main-page.jsx
> +  const currentMovie = movies[0];
Даже не знал, что так

2020-10-20 06:02 UTC, abeluzhenko approved these changes

2020-10-20 06:02 UTC, abeluzhenko commented on src/mocks/films.js
> +].map((item) => (Object.assign({}, item, {id: nanoid()})));
Можно проще, т.к. можем мутировать аргумент: `Object.assign(item, {id: nanoid()})`

2020-10-20 06:03 UTC, merged