Module4 task1
htmlacademy-react/54972-what-to-watch-5 pull request #6
Opened 2020-10-21 14:20 UTC by AeShevch

2020-10-23 06:42 UTC, abeluzhenko requested changes

2020-10-23 06:42 UTC, abeluzhenko commented on src/components/movies-list/movies-list.jsx
> +        }, 1000);
Было бы круто завести константу с этим значением

2020-10-25 11:06 UTC, AeShevch commented on src/components/movies-list/movies-list.jsx
> +      activeMovieIndex: `-1`,
Не знал, думал, что всё, что берётся из атрибутов - строка

2020-10-25 11:07 UTC, AeShevch commented on src/components/movies-list/movies-list.jsx
> +    evt.persist();
Без persist пустой evt.currentTarget, а он мне там нужен. Как тогда быть?

2020-10-26 05:16 UTC, abeluzhenko approved these changes

2020-10-26 05:16 UTC, merged